spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demojpa
    username:  root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update  #từ động đồng bộ model với database
    generate-ddl: true
    show-sql: true